spring:
  application:
    name: product-service
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:productdatabase
    username: user
    password: user@123
  liquibase:
    enabled: true
    user: user
    password: user@123
    change-log: classpath:db/changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: none
      database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
  h2:
    console:
      enabled: true
      path: /console
